
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: map-development

test:
  <<: *default
  database: map-test

production:
  <<: *default
  database: map-production
